name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_docker:
    name: Building docker image
    runs-on: ubuntu-latest
    steps:
    
    # check out code
    - uses: actions/checkout@v2
    
    # log into docker hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    # build docker img
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag  bram2202/test-docker-html
    
    - name: Docker buildX
      run: |
           docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6,linux/s390x \
            -t bram2202/test-docker-html \
            --push \
            .
      
    # push to docker hub
    - name: docker push
      run: docker push bram2202/test-docker-html
